apiVersion: v1
kind: Secret
metadata:
  name: tia-secret
type: Opaque
stringData:
  AUTH_PROVIDER_X509_CERT_URL: ${AUTH_PROVIDER_X509_CERT_URL}
  AUTH_URI: ${AUTH_URI}
  BUCKET_ID: ${BUCKET_ID}
  CLIENT_EMAIL: ${CLIENT_EMAIL}
  CLIENT_ID: '${CLIENT_ID}'
  CLIENT_X509_CERT_URL: ${CLIENT_X509_CERT_URL}
  DATABASE_URL: ${DATABASE_URL}
  DB_NAME: ${DB_NAME}
  DB_URI: ${DB_URI}
  NODE_ENV: ${NODE_ENV}
  PRIVATE_KEY: ${PRIVATE_KEY}
  PRIVATE_KEY_ID: ${PRIVATE_KEY_ID}
  PROJECT_ID: ${PROJECT_ID}
  SESSION_SECRET: ${SESSION_SECRET}
  TOKEN_URI: ${TOKEN_URI}
  TYPE: ${TYPE}
